### ISSUE TITLE
responsiveness for all devices

### ISSUE THREAD

**Issue by DaniJobe** [viestat/gdevcon-demo-js#5]
![image](https://user-images.githubusercontent.com/19363262/44842893-4d0aa980-ac47-11e8-9ef0-68ad12972b3d.png)
for some reason the HTML container is smaller than the device window

**Comment by DanielleJobe** [comment]
![image](https://user-images.githubusercontent.com/19363262/44843371-7a0b8c00-ac48-11e8-90b9-b629edd6ff35.png)
 If max-width is taken away this is fixed
